<a href="https://colab.research.google.com/github/thidark/Machine-Learning-Python-/blob/main/0_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
print(3*9)

27


In [ ]:
x=10
y=20
x+y

30

In [ ]:
import numpy as np

In [ ]:
A=np.array([[20,30],[40,50],[60,70]])

In [ ]:
A

array([[20, 30],
       [40, 50],
       [60, 70]])

In [ ]:
print(A.shape)

(3, 2)


In [ ]:
print(A[1,1])

50


In [ ]:
print(A[1,0])

40


In [ ]:
y=np.array([[100],[200],[300],[400]])

In [ ]:
y

array([[100],
       [200],
       [300],
       [400]])

In [ ]:
print(y.shape)

(4, 1)


In [ ]:
B=np.array([1,2,3,4,5,6]).reshape(3,2)

In [ ]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B=np.array([1,2,3,4,5,6]).reshape(2,3)

In [ ]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
4*B

array([[ 4,  8, 12],
       [16, 20, 24]])

In [ ]:
B/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
A=np.array([1,2,3,4,5,6]).reshape(3,2)

In [ ]:
B=np.array([10,20,30,40]).reshape(2,2)

In [ ]:
C=np.dot(A,B)

In [ ]:
C

array([[ 70, 100],
       [150, 220],
       [230, 340]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
A.dot(B)

array([[ 70, 100],
       [150, 220],
       [230, 340]])

In [ ]:
C=np.array([2,1,2,1]).reshape(2,2)

In [ ]:
C

array([[2, 1],
       [2, 1]])

In [ ]:
A=np.array([1,2,3,4]).reshape(2,2)

In [ ]:
(A@B)@C

array([[340, 170],
       [740, 370]])

In [ ]:
A@(B@C)

array([[340, 170],
       [740, 370]])

In [ ]:
np.dot(A,B)

array([[ 70, 100],
       [150, 220]])

In [ ]:
A@B@C

array([[340, 170],
       [740, 370]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
I=np.eye(2)

In [ ]:
A @ I

array([[1., 2.],
       [3., 4.]])

In [ ]:
I @ A

array([[1., 2.],
       [3., 4.]])

In [ ]:
Ainverse=np.linalg.inv(A)

In [ ]:
Ainverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
A @ Ainverse

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
x=np.array([[1,3],[2,5]])

In [ ]:
x


array([[1, 3],
       [2, 5]])

In [ ]:
xin=np.linalg.inv(x)

In [ ]:
xin

array([[-5.,  3.],
       [ 2., -1.]])

In [ ]:
x @ xin

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.transpose(x) 

array([[1, 2],
       [3, 5]])

In [ ]:
x.transpose()

array([[1, 2],
       [3, 5]])